services:
  storage:
    image: minio/minio:latest
    container_name: storage_minio
    hostname: storage
    environment:
      MINIO_ACCESS_KEY: ${STORAGE_ACCESS_KEY}
      MINIO_SECRET_KEY: ${STORAGE_SECRET_KEY}
    ports:
      - '9000:9000'
      - '9001:9001'
    command: server /data --console-address ":9001"
    restart: always
    volumes:
      - 'minio_data:/data'
    networks:
      - storage
    extra_hosts:
      - 'host.docker.internal:host-gateway'
networks:
  storage:
    driver: bridge

volumes:
  minio_data:
    driver: local
